Innoactive/XR-Interaction-Component

Runtime/Properties/GrabbableProperty.cs, Runtime/Properties/SnapZoneProperty.cs, Runtime/Properties/TouchableProperty.cs, Runtime/Properties/UsableProperty.cs
we only got the reference to the interactable OnEnable which caused a npe when disabled objects where locked. Fixed it by adding a getter which cares about that.
=> fix: fixed possible NRE when properties start disabled

Runtime/Properties/SnappableProperty.cs
**Fixes**: # The SnappProperty was not implementing the LockProperty thus it was not considered in the restrictive environment. This PR fixes it.
=> The SnappableProperty is now lockable and prevents NRE if it is locked while it is disabled.

Runtime/Properties/SnappableProperty.cs
=> fix: add new keyword to overriden method

Editor/Properties/SnappablePropertyEditor.cs
**Fixes**: An issue when generating a snap zone from a snappable object with special characters like / or \ 
Create a snappable object named with invalid characters, generate a snap zone from it.
=> The Snap Zone generator now handles invalid characters TRNG-1045

Editor/Properties/SnappablePropertyEditor.cs
**Fixes**: An issue where the scale of Snap Zones generated from snappable objects child of another object, was off.
1. Create an empty game object.
1. Create a cube inside the game object.
1. Set random position, rotation, and scale for both.
1. Add a snappable property to the cube.
1. Create a snap zone from the snap zone generator button in the snappble property (the cube).
The Snap Zone should imitate the position, rotation, and scale of the cube.
=> Scale of automated snap zones is always right. TRNG-1043

Runtime/Properties/GrabbableProperty.cs, Runtime/Properties/HighlightProperty.cs, Runtime/Properties/SnappableProperty.cs, Runtime/Properties/TouchableProperty.cs, Runtime/Properties/UsableProperty.cs
If the GameObject has not been an interactable object before, when adding the `HighlightProperty` it adds the `InteractableObject` component but disables the `IsTouchable`, `IsGrabbable`, and `IsUsable` flags. Besides, the added rigidbody is set to kinematic.
If the GameObject has been an interactable object before, the `InteractableObject` and rigidbody stay as they are.
Furthermore, the `TouchableProperty`, `GrabbableProperty`, and `UsableProperty` also make sure to set the flags properly after being added to the GameObject.
This bugfix uses the [MonoBehaviour.Reset](https://docs.unity3d.com/ScriptReference/MonoBehaviour.Reset.html) method by Unity.
**Fixes**: [TRNG-1033](https://jira.innoactive.de/browse/TRNG-1033)
Adding each property (`HighlightProperty`. `TouchableProperty`, …
=> fix: highlight property does not automatically add interactability

Editor/Properties/SnappablePropertyEditor.cs, Runtime/Interaction/SnapZone.cs, Runtime/Properties/GrabbableProperty.cs, Runtime/Properties/SnapZoneProperty.cs
A fix that add an attach transform when you add a snap zone property to an object. It sets its offset to the collider's offset, if the snap zone has one.
I added and reset snap zone properties for empty game object, for game objects with physical colliders only, for game objects with sphere, capsule, and cube with an offset.
=> fix: add transform and offset it to the snap zone collider

Runtime/Interaction/SnapZone.cs
Snappable objects when fast forwarded "hit"other objects on their way to the SnapZone cause those objects to fly away. Now the objects are first moved to the snap zones position before they eventually snap.
**Fixes**: TRNG-1069
Set up 8 objects in a row and 8 SnapZones behind them. Snapping the first object into the first SnapZone so it has to "pass through" all other objects.
=> fix: fast forward snappables now snap immediately

Runtime/Interaction/Highlighters/InteractableHighlighter.cs
The InteractableHighlighter only drew the first submesh of the mesh filter.
Now it draws all submeshes.
**Fixes**: # [TRNG-1061](https://jira.innoactive.de/browse/TRNG-1061)
Using different objects with multiple meshes (submeshes) like the winkelschrauber.fbx provided in this ticket. Then highlight it with the highlight behavior.
**Test Configuration**:
- [x ] My code follows the [Coding Conventions](#coding-conventions)
=> fix: highlight now draws all submeshes not only the first

Editor/Properties/SnappablePropertyEditor.cs, Runtime/Interaction/InteractableObject.cs
The Snap Zone generator used to generate highlight objects with materials for the main mesh but not for the submeshes, this pr adds render support for those submeshes.
Create a snap zone from a snappable property with sub meshes.
=> fix: highlight object is now created rendering all sub meshes

Runtime/Interaction/SnapZone.cs
This commit fixes a NullReferenceException which primarly happened when creating a highlight prefab of a snap zone that has other snap zones as children.
Create a snap zone of an object which has snap zones as children with the generator.
=> fix: snap zone highlight creation ignores empty meshes now

Runtime/Properties/HighlightProperty.cs
The HighlightProperty tests were broken since MonoBehaviour.Reset() is not called during runtime.
It now initializes the Highlighter also in the MonoBehaviour.OnEnable() method,
when the MonoBehaviour.Reset() was not called before in editor.
Run all test cases and manually tested "fix it" buttons again.
=> fix: fix HighlightProperty tests

Resources/[XR_Setup].prefab
**Fixes**: Weird offset in the camera of the xr prefab.
Set the scene as a training scene and check the xr camera offset, it must be at 0,0,0
=> chore: the xr prefab places the camera at its origin TRNG-1025

Runtime/Interaction/SnapZone.cs
If a Snap Zone started a scene nested in an interactable object, the colliders of the snap zone were grabbable as an extension of the interactable object. This PR fixes this behavior.
**Note:** It is still possible to manually set the snap zones colliders as part of the interactable object. 
Place a snap zone inside an interactable object, then run the scene an try to grab the interactable object by the snap zone, it should not be possible anymore.
=> feat: nested snap zone is not grabbable by default

Runtime/Interaction/InteractableObject.cs, Runtime/Interaction/SnapZone.cs
Fixed the highlighting by running a own list which is not limited to a unique reference to the object. So each collider is handled separately and as long as there is at least one collider inside the snapzone its highlighted.
The way I tested this was with the box from the XR-CKD Demo Project which contains multiple collider. I also figgured out the problem actually occured more often when one Collider was completely surrounded by another one.
=> fix: highlighting improved for interactables with multiple collider

Editor/SnapZone/SnapZoneSettings.cs
When the snap zone settings were lost, a new material was created. It overrid the old default material. This lead to losing the validation material in previous configured snap zones because the old material was removed.
**Fixes**: [TRNG-1070](https://jira.innoactive.de/browse/TRNG-1070)
1. Create a snap zone with the generator
2. Play scene
3. Stop scene
4. Create new snap zones with the generator
5. Sporadically the previous (old) snap zones lost the validation material
6. Somehow sometimes the settings were set to null and thus a new validation material was created which overrid the old material. Thus all old snap zones lost their validation material.
=> fix: snap zones do not lose validation material anymore

Editor/Properties/SnappablePropertyEditor.cs, Runtime/Interaction/InteractableObject.cs, Runtime/Interaction/SnapZone.cs, Runtime/Properties/GrabbableProperty.cs, Runtime/Properties/TouchableProperty.cs
**Fixes**: If after a touch condition there is a disabled behavior that disables the same object that was previously touched, the controller that touched the object stops interacting (no more touch or grab), this can be reverted after the user uses that controller for teleporting or to show the UI ray controller.
Make a course where you have to touch something, the next step right after the touch condition, disable the very same object (like in CKD when the user has to touch the button on the screen), then try to touch or grab another object.
If the same procedure is also applied for a grab condition, the controller also gets disabled. That is another issue that will have its own ticket.
=> Controllers do not stop interacting after a touch condition

Runtime/Interaction/InteractableObject.cs, Runtime/Interaction/SnapZone.cs
throwing things into the snapzone made it force snap before the normal snap behavior was triggered. Fixed by only force snapping when the object was, beforehand grabbed.
=> fix: snappable will be properly snapped to snapzones when thrown

Runtime/Interaction/InteractableObject.cs, Runtime/Interaction/SnapZone.cs
To properly select/snap an object the object snapped also have to call OnSelectEnter.
to test:
Step1: Snap an object do a snapzone
Step2: do something else
=> run the course, fast forward to step2, see if the snapped object moves when the snapzone is moved.
=> fix: force select properly attaches object now

Runtime/Interaction/Highlighters/InteractableHighlighter.cs
**Fixes**: Objects that were disabled while being highlighted used to lose their renderer, this was only noticeable when they were enabled again.
Create a course with 3 steps: 
- Step 1 highlights an object.
- Step 2 disables that object.
- Step 3 enables it again.
=> fix: highlighted objects recover their renderer when they become disabled

Runtime/Interaction/SnapZone.cs
**Fixes**: Snap zones were locked before they were reparented.
Detaching and reattaching is made so if the parent is an interactable object then it does not consider snap zones colliders as valid colliders for it.
Try CKD
=> fix: snap zones are not locked while detached from their parent.

Editor/Interaction/InteractableHighlighterEditor.cs, Runtime/AssemblyAttributes.cs, Runtime/AssemblyAttributes.cs.meta, Runtime/Interaction/Highlighters/InteractableHighlighter.cs, Runtime/Interaction/SnapZone.cs, Tests/Runtime/HighlightObjectTests.cs
fix: the preview highlight mesh is now cached in the editor
fix: the preview highlight mesh does not have an offset
**Fixes**: An issue that used to highlight baked meshes (static objects) along with other baked meshes. 
Use the `Highlight Behavior` to highlight a static object.
Before:
After:
Complex objects with multiple renderers and submeshes either static and non static being highlighted at the same time.
=> fix: batched meshes are prevented to be highlighted

Runtime/Interaction/Highlighters/InteractableHighlighter.cs, Runtime/Interaction/SnapZone.cs
**Fixes**: In some scenarios, children objects of a highlighted object were incorrectly rendered at its origin.
It also solves the same issue for snap zones.
Use the highlight behavior with an object with some children.
Create a snap zone from an object with some children.
=> Hotfix for children of a highlighted object

Editor/Innoactive.CreatorEditor.XRInteraction.asmdef, Editor/PackageDependencies/XRInteractionPackageEnabler.cs
Since Unity updated its "XR Interaction Framework" package to v0.10.0-preview.7,
our Creator component is not compatible to it anymore.
For the next release, we use the older compatible version v0.9.4-preview.
**Fixes**:  [TRNG-1272](https://jira.innoactive.de/browse/TRNG-1272)
Imported the Creator and all its components (including the XR-Interaction-Component). It now uses the compatible v0.9.4-preview version instead of the newest v0.10.0-preview.7 version which is incompatible.
=> fix: use specific Unity XR Interaction Toolkit package

Runtime/Interaction/DirectInteractor.cs
**Fixes**: An issue that appears in interactable objects that have attach transform points after previously grab objects without attach transform points.
Grab an object that does not have an attach transform (it should be grabbed using precision grab), then grab another object that has an attach transform (it should be grabbed from the attach transform position).
=> fix: offset when grabbing multiple objects with attach points TRNG-1288

Editor/Innoactive.CreatorEditor.XRInteraction.asmdef, Editor/Interaction/DirectInteractorEditor.cs, Editor/Interaction/InteractableHighlighterEditor.cs, Editor/Interaction/InteractableObjectEditor.cs, Editor/Interaction/RayInteractorEditor.cs, Editor/Interaction/SnapZoneEditor.cs, Editor/PackageDependencies/InputSystemChecker.cs, Editor/PackageDependencies/InputSystemChecker.cs.meta, Editor/PackageDependencies/XRInteractionPackageEnabler.cs, Editor/Properties/SnappablePropertyEditor.cs, Editor/SnapZone/SnapZoneSettings.cs, Runtime/Innoactive.Creator.XRInteraction.asmdef, Runtime/Interaction/DirectInteractor.cs, Runtime/Interaction/Highlighters/InteractableHighlighter.cs, Runtime/Interaction/InteractableObject.cs, Runtime/Interaction/SnapZone.cs, Runtime/Properties/GrabbableProperty.cs, Runtime/Properties/SnapZoneProperty.cs, Runtime/Properties/SnappableProperty.cs, Runtime/Properties/TouchableProperty.cs, Tests/Runtime/Innoactive.Creator.XRInteraction.Tests.asmdef, Tests/Runtime/SnapZoneTests.cs
feat: component is compatible with older IXIT versions
feat: multiple interactables and interactors can now be edited at the same time
**Fixes**: Incompatibility with the latest XR Interaction Toolkit version.
Importing different versions of the XR Interaction Toolkit.
=> The XR component is now compatible with IXIT v1.0.0-pre.1 TRNG-1271

Runtime/Innoactive.Creator.XRInteraction.asmdef, Runtime/Interaction/Interactables/InteractableHighlighter.cs, Runtime/Interaction/Interactables/InteractableObject.cs, Runtime/Interaction/Interactors/DirectInteractor.cs, Runtime/Interaction/Interactors/SnapZone.cs, Runtime/Properties/GrabbableProperty.cs, Runtime/Properties/SnapZoneProperty.cs, Runtime/Properties/SnappableProperty.cs, Runtime/Properties/TouchableProperty.cs, Runtime/Properties/UsableProperty.cs
The latest XRIT release (`1.0.0-pre.2` January 25) changed the signature of all interaction event methods causing the Creator to have 50 warnings from obsolete methods:
This PR fixes all, it also provides backward compatibility from `0.9.3-preview` to the current `1.0.0-pre2`.
From the `Package Manager` jump between different versions of the `XR Interaction Toolkit` package, the Creator should work on all from the listed range.
=> XRIT API update

Editor/Innoactive.CreatorEditor.XRInteraction.asmdef, Editor/Interaction/InteractableObjectEditor.cs, Editor/XRInteractionSceneSetup.cs, Runtime/Rigs/XRSetupBase.cs
**Fixes**: 
- An issue where selecting an interactable object while been on the latest XRIT will throw multiple errors in the console.
- An issue where setting a training scene throws a warning.
=> fix: property name updated to latest XRIT API TRNG-1397

Runtime/Properties/HighlightProperty.cs
The visual effect of the highlight property worked but it never set the IsHighlighted flag to true.
**Fixes**: # (issue)
=> fix: highlight property flags itself highlighted now

Runtime/Rigs/XRLegacySetup.cs, Runtime/Rigs/XRSetup.cs, Runtime/Rigs/XRSetupBase.cs, Runtime/Rigs/XRSimulatorSetup.cs
The `Interaction Rig Loader` now validates that the prefabs exist for each rig.
https://user-images.githubusercontent.com/6911992/107626432-116cca00-6c5e-11eb-8c56-22775bbf1208.mp4
Try renaming, moving out from the `Resources` folder, or deleting the XR Rig prefabs, the `Interaction Rig Loader` should mark a Rig as invalid if its corresponding prefab is missing.
For testing purposes, the `[XR_Setup_Simulator]` can be deleted from the `XR-Interaction-Component/Resources` and regenerate by setting again the training scene from the innoactive menu.
=> fix: rig loader now validates that prefab exits

.gitignore, Editor/Innoactive.CreatorEditor.XRInteraction.asmdef, Editor/Interaction/DirectInteractorEditor.cs, Editor/Interaction/InteractableObjectEditor.cs, Editor/Interaction/RayInteractorEditor.cs, Editor/Interaction/SnapZoneEditor.cs, Editor/PackageDependencies/XRInteractionPackageEnabler.cs, Editor/SceneSetup/XRInteractionSceneSetup.cs, Editor/SceneSetup/XRSimulatorImporter.cs, Editor/SnapZone/SnapZoneSettings.cs, Runtime/Innoactive.Creator.XRInteraction.asmdef, Runtime/Interaction/Action-based/ActionBasedControllerManager.cs, Runtime/Interaction/Action-based/LocomotionSchemeManager.cs, Runtime/Interaction/Interactables/InteractableHighlighter.cs, Runtime/Interaction/Interactables/InteractableObject.cs, Runtime/Interaction/Interactors/DirectInteractor.cs, Runtime/Interaction/Interactors/SnapZone.cs, Runtime/Properties/GrabbableProperty.cs, Runtime/Properties/SnapZoneProperty.cs, Runtime/Properties/SnappableProperty.cs, Runtime/Properties/TouchableProperty.cs, Runtime/Properties/UsableProperty.cs, Runtime/Rigs/XRSimulatorSetup.cs
XRIT is now always at v1.0.0-pre.2
- https://github.com/Innoactive/Creator/pull/261
Try any course in VR.
=> Component now uses XRIT at v1.0.0-pre.2 TRNG-1463

Runtime/Interaction/Interactors/SnapZone.cs
Fixed highlighting of snapzones for the case that mode parameters are used.
With Modesexample scene
=> fix: snapzone mode parameters now work
